apiVersion: v2
name: hot-website
description: HOT Website Helm Chart

type: application
icon: https://hotosm.org/static/images/favicon-16x16.png
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.8

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0.8"

dependencies:
  - name: dragonfly
    version: v1.38.0
    repository: oci://ghcr.io/dragonflydb/dragonfly/helm
    alias: dragonfly
