# Generated by Django 4.2.7 on 2024-05-07 22:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('program', models.CharField(blank=True)),
                ('location', models.CharField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('description', wagtail.fields.StreamField([], null=True, use_json_field=True)),
                ('call_to_action_title', models.CharField(default='Call to Action')),
                ('call_to_action_description', wagtail.fields.RichTextField(null=True)),
                ('call_to_action_link', models.CharField(default='Call to Action Link')),
                ('impact_areas_title', models.CharField(default='Impact Areas')),
                ('impact_areas', models.CharField(null=True)),
                ('region_hub_title', models.CharField(default='Region Hub')),
                ('region_hub', models.CharField(null=True)),
                ('duration_title', models.CharField(default='Duration')),
                ('duration', models.CharField(default='Ongoing')),
                ('partners_title', models.CharField(default='Partners')),
                ('partners', models.CharField(null=True)),
                ('tools_title', models.CharField(default='Tools')),
                ('tools', models.CharField(null=True)),
                ('contact_title', models.CharField(default='Contact')),
                ('contact', models.EmailField(max_length=254, null=True)),
                ('related_news_title', models.CharField(default='Related News')),
                ('view_all_news_text', models.CharField(default='View all News')),
                ('related_events_title', models.CharField(default='Related Events')),
                ('view_all_events_text', models.CharField(default='View all Events')),
                ('red_box_title', models.CharField(default='Chat with Our Community')),
                ('red_box_link_text', models.CharField(default='Get connected now')),
                ('red_box_link_url', models.URLField(null=True)),
                ('black_box_title', models.CharField(default='Our Work')),
                ('black_box_link_text', models.CharField(default='View Our Work')),
                ('black_box_link_url', models.URLField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
