# Generated by Django 4.2.7 on 2024-05-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='black_box_link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='red_box_link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
