# Generated by Django 4.2.7 on 2024-05-07 22:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_individualprojectpage_black_box_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='description',
            field=wagtail.fields.StreamField([('bodytext', wagtail.blocks.RichTextBlock())], null=True, use_json_field=True),
        ),
    ]
