# Generated by Django 4.2.7 on 2024-05-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('projects', '0004_alter_individualprojectpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
