# Generated by Django 4.2.7 on 2024-05-08 18:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_individualprojectpage_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='description',
            field=wagtail.fields.StreamField([('text_block', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'blockquote']))], null=True, use_json_field=True),
        ),
    ]
