# Generated by Django 4.2.7 on 2024-05-08 19:12

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_individualprojectpage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualprojectpage',
            old_name='call_to_action_link',
            new_name='call_to_action_link_text',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='call_to_action_link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='black_box_link_text',
            field=wagtail.fields.RichTextField(default='View Our Work'),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='call_to_action_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='contact',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='duration',
            field=models.CharField(blank=True, default='Ongoing'),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='impact_areas',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='partners',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='red_box_link_text',
            field=wagtail.fields.RichTextField(default='Get connected now'),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='region_hub',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='tools',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
