# Generated by Django 4.2.7 on 2024-05-14 17:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_call_to_action_link_individualprojectpage_call_to_action_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='related_news',
            field=wagtail.fields.StreamField([('news_page', wagtail.blocks.PageChooserBlock(page_type=['news.IndividualNewsPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
