# Generated by Django 4.2.7 on 2024-05-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('projects', '0009_remove_individualprojectpage_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='region_hub',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='owner_region_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
