# Generated by Django 4.2.7 on 2024-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_individualprojectpage_region_hub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='black_box_link_text',
            field=models.CharField(default='View Our Work'),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='red_box_link_text',
            field=models.CharField(default='Get connected now'),
        ),
    ]
