# Generated by Django 4.2.7 on 2024-05-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_individualprojectpage_black_box_link_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='impact_areas',
        ),
    ]
