# Generated by Django 4.2.7 on 2024-05-23 22:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_individualprojectpage_impact_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='impact_area_list',
            field=wagtail.fields.StreamField([('impact_area', wagtail.blocks.PageChooserBlock(page_type=['impact_areas.IndividualImpactAreaPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
