# Generated by Django 4.2.7 on 2024-06-03 21:40

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_partner_partner_logo_alter_partner_partner_url'),
        ('projects', '0014_alter_individualprojectpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='partners',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='partners_list',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.partner'),
        ),
    ]
