# Generated by Django 4.2.7 on 2024-06-04 17:21

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_individualprojectpage_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='project_contributors',
            field=wagtail.fields.StreamField([('contributor', wagtail.blocks.PageChooserBlock(page_type=['members.IndividualMemberPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
