# Generated by Django 4.2.7 on 2024-06-04 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('projects', '0017_alter_individualprojectpage_project_contributors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('impact_areas_title', models.CharField(default='Impact Areas')),
                ('region_hub_title', models.CharField(default='Region Hub')),
                ('duration_title', models.CharField(default='Duration')),
                ('partners_title', models.CharField(default='Partners')),
                ('tools_title', models.CharField(default='Tools')),
                ('contact_title', models.CharField(default='Contact')),
                ('related_news_title', models.CharField(default='Related News')),
                ('view_all_news_text', models.CharField(default='View all News')),
                ('related_events_title', models.CharField(default='Related Events')),
                ('view_all_events_text', models.CharField(default='View all Events')),
                ('red_box_title', models.CharField(default='Chat with Our Community')),
                ('red_box_link_text', models.CharField(default='Get connected now')),
                ('red_box_link_url', models.URLField(blank=True, null=True)),
                ('black_box_title', models.CharField(default='Our Work')),
                ('black_box_link_text', models.CharField(default='View Our Work')),
                ('black_box_link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
