# Generated by Django 4.2.7 on 2024-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectownerpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='view_all_events_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='view_all_news_url',
            field=models.URLField(blank=True),
        ),
    ]
