# Generated by Django 4.2.7 on 2024-06-05 23:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_individualprojectpage_black_box_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='related_events',
            field=wagtail.fields.StreamField([('event_page', wagtail.blocks.PageChooserBlock(page_type=['events.IndividualEventPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
