# Generated by Django 4.2.7 on 2024-06-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_individualprojectpage_related_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='load_more_projects_text',
            field=models.CharField(default='Load More Projects'),
        ),
    ]
