# Generated by Django 4.2.7 on 2024-07-04 18:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_individualprojectpage_owner_region_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='region_hub_list',
            field=wagtail.fields.StreamField([('region_hub', wagtail.blocks.PageChooserBlock(page_type=['mapping_hubs.IndividualMappingHubPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
