# Generated by Django 4.2.7 on 2024-08-08 22:40

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_individualprojectpage_project_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='project_active',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='project_status',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='projects.projectstatus'),
        ),
    ]
