# Generated by Django 4.2.7 on 2024-08-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_projectstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project statuses'},
        ),
    ]
