# Generated by Django 4.2.7 on 2024-08-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_projectstatus_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='project_status',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='project_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectstatus'),
        ),
    ]
