# Generated by Django 4.2.7 on 2024-08-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_remove_individualprojectpage_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='types_title',
            field=models.CharField(default='Project Type'),
        ),
    ]
