# Generated by Django 4.2.7 on 2024-09-09 23:12

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectownerpage_types_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='tools',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='tools_list',
            field=wagtail.fields.StreamField([('tool', wagtail.blocks.PageChooserBlock(page_type=['tech.IndividualTechStackPage']))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='location_coordinates',
            field=models.CharField(blank=True, help_text='Used to show where on the map the project takes place; used on the Our Work page.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='project_contributors',
            field=wagtail.fields.StreamField([('contributor', wagtail.blocks.PageChooserBlock(page_type=['members.IndividualMemberPage']))], blank=True, help_text="If a member is listed as a contributor to a project, that project will appear on the given member's page.", null=True, use_json_field=True),
        ),
    ]
