# Generated by Django 4.2.7 on 2024-09-18 21:59

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_remove_individualprojectpage_tools_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprojectpage',
            name='call_to_action_link_url',
        ),
        migrations.RemoveField(
            model_name='projectownerpage',
            name='black_box_link_url',
        ),
        migrations.RemoveField(
            model_name='projectownerpage',
            name='red_box_link_url',
        ),
        migrations.RemoveField(
            model_name='projectownerpage',
            name='view_all_events_url',
        ),
        migrations.RemoveField(
            model_name='projectownerpage',
            name='view_all_news_url',
        ),
        migrations.AddField(
            model_name='individualprojectpage',
            name='call_to_action_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='black_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='red_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='view_all_events_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='view_all_news_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
