# Generated by Django 4.2.7 on 2024-10-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_alter_individualprojectpage_call_to_action_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name_plural': 'Project Statuses'},
        ),
        migrations.AlterModelOptions(
            name='projecttype',
            options={'verbose_name_plural': 'Project Types'},
        ),
    ]
