# Generated by Django 4.2.7 on 2024-10-21 21:37

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_alter_projectstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='description',
            field=wagtail.fields.StreamField([('text_block', 0)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote']})}, null=True),
        ),
    ]
