# Generated by Django 4.2.7 on 2024-10-24 23:02

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_alter_individualprojectpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='country_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='This field is not required; this field is mostly for projects with no specified region hub. Regardless, if region hub(s) and country are both provided, both fields will appear on the page.'),
        ),
        migrations.AlterField(
            model_name='projectownerpage',
            name='region_hub_title',
            field=models.CharField(default='Region Hub/Country'),
        ),
    ]
