# Generated by Django 4.2.7 on 2024-10-25 17:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_individualprojectpage_country_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='contact',
            field=wagtail.fields.RichTextField(blank=True, help_text='If you provide an email here, make sure to turn it into an email link. This can be done by highlighting the text containing the email and pressing CTRL + K.', null=True),
        ),
    ]
