# Generated by Django 4.2.7 on 2024-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_individualprojectpage_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='apply_filter_text',
            field=models.CharField(default='Apply Filter'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='impact_areas_text',
            field=models.CharField(default='Impact Areas'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='open_mapping_hubs_text',
            field=models.CharField(default='Open Mapping Hubs'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='project_status_text',
            field=models.CharField(default='Project Status'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='projects_by_programme_text',
            field=models.CharField(default='Projects by Programme'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='projects_by_type_text',
            field=models.CharField(default='Projects by Type'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='reset_filters_text',
            field=models.CharField(default='Reset Filters'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='search_keyword_text',
            field=models.CharField(default='Search by keyword'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='sort_new_text',
            field=models.CharField(default='Sort by New'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='sort_old_text',
            field=models.CharField(default='Sort by Old'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='sort_titlea_text',
            field=models.CharField(default='Sort by Name Alphabetical'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='sort_titlez_text',
            field=models.CharField(default='Sort by Name Reverse Alphabetical'),
        ),
    ]
