# Generated by Django 4.2.7 on 2024-11-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_remove_projectownerpage_sort_new_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='applied_text',
            field=models.CharField(default='applied'),
        ),
        migrations.AlterField(
            model_name='projectownerpage',
            name='impact_areas_text',
            field=models.CharField(default='Filter by Impact Area'),
        ),
        migrations.AlterField(
            model_name='projectownerpage',
            name='open_mapping_hubs_text',
            field=models.CharField(default='Filter by Hub'),
        ),
        migrations.AlterField(
            model_name='projectownerpage',
            name='project_status_text',
            field=models.CharField(default='Filter by Status'),
        ),
        migrations.AlterField(
            model_name='projectownerpage',
            name='projects_by_programme_text',
            field=models.CharField(default='Filter by Program'),
        ),
        migrations.AlterField(
            model_name='projectownerpage',
            name='projects_by_type_text',
            field=models.CharField(default='Filter by Type'),
        ),
    ]
