# Generated by Django 4.2.7 on 2024-11-07 22:09

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_projectownerpage_results_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='bottom_dogear_link',
            field=wagtail.fields.StreamField([('page', 0), ('url', 1), ('document', 2), ('other', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."})}),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='bottom_dogear_link_text',
            field=models.CharField(default='Check our work'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='bottom_dogear_title',
            field=models.CharField(default='See our projects on the map'),
        ),
    ]
