# Generated by Django 4.2.7 on 2025-03-20 15:57

import app.core.models
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_alter_individualprojectpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='partner_list',
            field=wagtail.fields.StreamField([('partner', 0), ('manual_partner', 1)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (app.core.models.Partner,), {}), 1: ('wagtail.blocks.CharBlock', (), {})}, null=True),
        ),
    ]
