# Generated by Django 4.2.7 on 2025-03-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_individualprojectpage_duration_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='duration_ongoing',
            field=models.CharField(default='Ongoing'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='duration_until',
            field=models.CharField(default='Until'),
        ),
    ]
