# Generated by Django 4.2.7 on 2025-03-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_individualprojectpage_is_community_led_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='community_led_text',
            field=models.CharField(default='Community Led', help_text='If a project is community led, this text will appear in the header.'),
        ),
    ]
