# Generated by Django 4.2.7 on 2025-03-21 23:22

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_projectownerpage_community_led_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='project_contributors',
            field=wagtail.fields.StreamField([('contributor', 0), ('manual_contributor', 1)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['members.IndividualMemberPage']}), 1: ('wagtail.blocks.CharBlock', (), {})}, help_text="If a member is listed as a contributor to a project, that project will appear on the given member's page. Please refrain from adding new Manual Contributors; the option was created primarily for data preservation after page migration from the previous HOT website.", null=True),
        ),
    ]
