# Generated by Django 4.2.7 on 2025-03-24 23:16

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_alter_individualprojectpage_tools_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprojectpage',
            name='data_links',
            field=wagtail.fields.StreamField([('data', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 1)]], {})}, null=True),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='data_title',
            field=models.CharField(default='Data'),
        ),
    ]
