# Generated by Django 4.2.7 on 2025-03-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_individualprojectpage_data_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprojectpage',
            name='call_to_action_link_text',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualprojectpage',
            name='call_to_action_title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
