# Generated by Django 4.2.7 on 2025-03-24 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('projects', '0058_alter_individualprojectpage_call_to_action_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectownerpage',
            name='fallback_image',
            field=models.ForeignKey(blank=True, help_text='If no cover image is provided for a news post, this image will display instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
