# Generated by Django 5.2.16 on 2026-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_projectownerpage_fallback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectownerpage',
            name='sort_titlea_text',
        ),
        migrations.RemoveField(
            model_name='projectownerpage',
            name='sort_titlez_text',
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='sort_newest_text',
            field=models.CharField(default='Newest First'),
        ),
        migrations.AddField(
            model_name='projectownerpage',
            name='sort_oldest_text',
            field=models.CharField(default='Oldest First'),
        ),
    ]
