# Generated by Django 4.2.7 on 2024-08-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourworkpage',
            name='f_project_active_text',
        ),
        migrations.RemoveField(
            model_name='ourworkpage',
            name='f_project_complete_text',
        ),
    ]
