# Generated by Django 4.2.7 on 2024-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerwithuspage',
            name='black_box_link_url',
            field=models.EmailField(default='partnerships@hotosm.org', max_length=254),
        ),
    ]
