# Generated by Django 4.2.7 on 2024-07-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerwithuspage_black_box_link_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerwithuspage',
            old_name='black_box_link_url',
            new_name='black_box_link_email',
        ),
    ]
