# Generated by Django 4.2.7 on 2024-07-25 21:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('partners', '0003_rename_black_box_link_url_partnerwithuspage_black_box_link_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='This is shown in the header.')),
                ('filter_by_type_text', models.CharField(default='Filter by Type')),
                ('load_more_partners_text', models.CharField(default='Load More Partners')),
                ('red_box_title', models.CharField(default='Join a working group')),
                ('red_box_link_text', models.CharField(default='Working Groups')),
                ('red_box_link_url', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True)),
                ('black_box_title', models.CharField(default='Contact a mapping community')),
                ('black_box_link_text', models.CharField(default='Community Contact')),
                ('black_box_link_url', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
