# Generated by Django 4.2.7 on 2024-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_alter_ourpartnerspage_black_box_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartnerspage',
            name='filter_button_text',
            field=models.CharField(default='Submit'),
        ),
    ]
