# Generated by Django 4.2.7 on 2024-08-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_ourpartnerspage_filter_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerwithuspage',
            name='partnership_types',
        ),
    ]
