# Generated by Django 4.2.7 on 2024-08-13 21:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partnertype_type_description_partnertype_type_icon'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('partners', '0007_remove_partnerwithuspage_partnership_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartnerspage',
            name='call_to_action_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='call_to_action_link_text',
            field=models.CharField(default='Call to Action Link'),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='call_to_action_link_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='call_to_action_title',
            field=models.CharField(default='Call to Action'),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='meet_partners_title',
            field=models.CharField(default='Meet Our Partners'),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='related_news_title',
            field=models.CharField(default='Related News'),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='related_projects_title',
            field=models.CharField(default='Related Projects'),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='view_partners_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='view_partners_text',
            field=models.CharField(default='View All Partners'),
        ),
        migrations.CreateModel(
            name='PartnershipTemplatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_text', wagtail.fields.RichTextField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('related_projects', wagtail.fields.StreamField([('project_page', wagtail.blocks.PageChooserBlock(page_type=['projects.IndividualProjectPage']))], blank=True, null=True, use_json_field=True)),
                ('related_news', wagtail.fields.StreamField([('news_page', wagtail.blocks.PageChooserBlock(page_type=['news.IndividualNewsPage']))], blank=True, null=True, use_json_field=True)),
                ('featured_partners', modelcluster.fields.ParentalManyToManyField(blank=True, to='core.partner')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
