# Generated by Django 4.2.7 on 2024-09-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_alter_ourpartnerspage_black_box_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartnerspage',
            name='filter_by_hub',
            field=models.CharField(default='Filter by Hub'),
        ),
        migrations.AddField(
            model_name='ourpartnerspage',
            name='filter_by_program',
            field=models.CharField(default='Filter by Program'),
        ),
    ]
