# Generated by Django 4.2.7 on 2024-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_alter_ourpartnerspage_black_box_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartnerspage',
            name='applied_text',
            field=models.CharField(default='applied', help_text='This will be a suffix to a number, used to indicate how many filters are applied currently in some field.'),
        ),
    ]
