# Generated by Django 4.2.7 on 2024-07-17 22:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('misc', '0002_joinourconversationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinourconversationpage',
            name='black_box_link_text',
            field=models.CharField(default='Community Contact'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='black_box_title',
            field=models.CharField(default='Contact a mapping community'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='code_of_conduct_link_text',
            field=models.CharField(default='Code of Conduct'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='code_of_conduct_title',
            field=models.CharField(default='Please read our Code of Conduct'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='get_connected_blocks',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock())]))], blank=True, help_text='Blocks to be shown under the Get Connected section.', null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='get_connected_title',
            field=models.CharField(default='Get Connected!'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='This is shown in the header.'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='red_box_link_text',
            field=models.CharField(default='Working Groups'),
        ),
        migrations.AddField(
            model_name='joinourconversationpage',
            name='red_box_title',
            field=models.CharField(default='Join a working group'),
        ),
    ]
