# Generated by Django 4.2.7 on 2024-08-01 18:58

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0010_alter_privacypolicypage_question_block_button_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacypolicypage',
            old_name='body_text',
            new_name='brief_body_text',
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='body_sections',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('body', wagtail.blocks.RichTextBlock())]))], blank=True, help_text='Sections to be shown in the body following the table of contents; these sections will automatically populate the table of contents.', null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='table_of_contents_title',
            field=models.CharField(default='This Privacy Policy Contains the Following Sections:'),
        ),
    ]
