# Generated by Django 4.2.7 on 2024-08-14 22:45

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_documentcollectionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcollectionpage',
            name='documents',
            field=wagtail.fields.StreamField([('block', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('description', wagtail.blocks.RichTextBlock(blank=True, null=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
