# Generated by Django 4.2.7 on 2024-08-26 20:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('misc', '0014_alter_documentcollectionpage_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('global_office_title', models.CharField(default='Global Office')),
                ('global_office_text', wagtail.fields.RichTextField(blank=True)),
                ('send_message_title', models.CharField(default='Send us a message!')),
                ('first_name_text', models.CharField(default='First Name')),
                ('last_name_text', models.CharField(default='Last Name')),
                ('email_text', models.CharField(default='Email Address')),
                ('subject_text', models.CharField(default='Subject')),
                ('message_text', models.CharField(default='Message')),
                ('first_name_field_text', models.CharField(default='Enter your first name...')),
                ('last_name_field_text', models.CharField(default='Enter your last name...')),
                ('email_field_text', models.CharField(default='Enter your email address...')),
                ('subject_field_placeholder', models.CharField(default='Select')),
                ('subject_field_options', wagtail.fields.StreamField([('block', wagtail.blocks.StructBlock([('subject', wagtail.blocks.CharBlock(blank=True, null=True, required=False))]))], blank=True, null=True, use_json_field=True)),
                ('message_field_text', models.CharField(default='Enter your message...')),
                ('submit_button_text', models.CharField(default='Submit')),
                ('inquiries_title', models.CharField(default='Inquiries')),
                ('inquiries_text', models.CharField(blank=True)),
                ('office_locations_title', models.CharField(default='Office Locations')),
                ('office_locations_visit_page_text', models.CharField(default='Visit Page')),
                ('office_locations', wagtail.fields.StreamField([('block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, null=True, required=False)), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, null=True, required=False)), ('description', wagtail.blocks.RichTextBlock(blank=True, null=True, required=False))]))], blank=True, null=True, use_json_field=True)),
                ('dogear_box_title', models.CharField(default='We want to know what you think about HOT and our work.')),
                ('dogear_box_link_text', models.CharField(default='Send us your feedback')),
                ('dogear_box_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
