# Generated by Django 4.2.7 on 2024-08-27 17:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0016_alter_contactuspage_inquiries_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuspage',
            name='inquiries_text',
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='inquiries_blocks',
            field=wagtail.fields.StreamField([('block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(blank=True, null=True, required=False)), ('email', wagtail.blocks.EmailBlock(blank=True, null=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
