# Generated by Django 4.2.7 on 2024-08-28 16:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('misc', '0017_remove_contactuspage_inquiries_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkForHotPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_text', wagtail.fields.RichTextField(blank=True)),
                ('our_values_title', models.CharField(default='Our Values')),
                ('our_values_text', wagtail.fields.RichTextField(blank=True)),
                ('work_culture_title', models.CharField(default='Work Culture & Benefits')),
                ('work_culture_description', wagtail.fields.RichTextField(blank=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
