# Generated by Django 4.2.7 on 2024-08-28 21:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('misc', '0018_workforhotpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforhotpage',
            name='opportunities_button_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='opportunities_button_text',
            field=models.CharField(default='See all job opportunities'),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='opportunities_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='opportunities_image',
            field=models.ForeignKey(blank=True, help_text='Opportunities image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='opportunities_title',
            field=models.CharField(default='See Our Job Opportunities'),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='our_values_youtube_subtitle',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='our_values_youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='testimonials',
            field=wagtail.fields.StreamField([('block', wagtail.blocks.StructBlock([('description', wagtail.blocks.RichTextBlock(blank=True, null=True, required=False)), ('member', wagtail.blocks.PageChooserBlock(page_type=['members.IndividualMemberPage'], required=False)), ('image_override', wagtail.images.blocks.ImageChooserBlock(required=False)), ('name_override', wagtail.blocks.CharBlock(required=False)), ('title_override', wagtail.blocks.CharBlock(required=False)), ('hub_override', wagtail.blocks.PageChooserBlock(page_type=['mapping_hubs.IndividualMappingHubPage'], required=False))]))], blank=True, help_text="For any given testimonial, you can choose a member to be displayed, or you can alternatively manually provide the member's details; if both are provided, the manually-entered details will override any details fetched from the member's page.", null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='testimonials_title',
            field=models.CharField(default='What Our Staff Say'),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='work_culture_youtube_subtitle',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='work_culture_youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
