# Generated by Django 4.2.7 on 2024-09-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('misc', '0023_alter_documentcollectionpage_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workforhotpage',
            old_name='our_values_youtube_subtitle',
            new_name='our_values_subtitle',
        ),
        migrations.RenameField(
            model_name='workforhotpage',
            old_name='work_culture_youtube_subtitle',
            new_name='work_culture_subtitle',
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='our_values_image',
            field=models.ForeignKey(blank=True, help_text='If a YouTube URL is provided, the video will be prioritised over this image; if there is no URL provided, this image will show.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='workforhotpage',
            name='work_culture_image',
            field=models.ForeignKey(blank=True, help_text='If a YouTube URL is provided, the video will be prioritised over this image; if there is no URL provided, this image will show.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
