# Generated by Django 4.2.7 on 2024-09-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0024_rename_our_values_youtube_subtitle_workforhotpage_our_values_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforhotpage',
            name='work_culture_subtitle',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='workforhotpage',
            name='work_culture_youtube_url',
            field=models.URLField(blank=True, help_text="The YouTube link provided should be in the following format: 'https://www.youtube.com/embed/[slug]'. You can get this by right-clicking on the YouTube video player and pressing 'Copy embed code'; this will give you a full embed code, which you will need to take the embed URL from."),
        ),
    ]
