# Generated by Django 4.2.7 on 2024-09-23 22:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('misc', '0025_alter_workforhotpage_work_culture_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryFrameworkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock())], blank=True, use_json_field=True)),
                ('go_back_prefix_text', models.CharField(default='Go Back to', help_text="This text will be a prefix to the parent page of this current page, and the attached link will always go to the parent page; i.e., if this page is a child of the 'Work for HOT' page, and this field is 'Go Back to', the link will read 'Go Back to Work for HOT'.")),
                ('sidebar_block_title', models.CharField(default="HOT's Journey through Salary Transparency")),
                ('sidebar_block_description', wagtail.fields.RichTextField(blank=True)),
                ('sidebar_block_button_text', models.CharField(default='Read More')),
                ('sidebar_block_button_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
