# Generated by Django 4.2.7 on 2024-10-01 19:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0028_donatepage_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='other_ways_to_donate',
            field=wagtail.fields.StreamField([('block', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
    ]
