# Generated by Django 4.2.7 on 2024-10-08 17:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('misc', '0029_alter_donatepage_other_ways_to_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_description', wagtail.fields.RichTextField(blank=True)),
                ('map_title', models.CharField(default='Map Gallery')),
                ('map_view_all_text', models.CharField(default='View all maps')),
                ('map_view_all_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('video_title', models.CharField(default='Videos')),
                ('video_view_all_text', models.CharField(default='View more videos on YouTube')),
                ('video_view_all_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('video_previews', wagtail.fields.StreamField([('preview', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock()), ('short_desc', wagtail.blocks.CharBlock(help_text='This will show beneath the image.', required=False))], max_num=8, min_num=8))], blank=True, use_json_field=True)),
                ('image_title', models.CharField(default='Images')),
                ('image_view_all_text', models.CharField(default='View more images on Flickr')),
                ('image_view_all_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('image_previews', wagtail.fields.StreamField([('preview', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('short_desc', wagtail.blocks.CharBlock(help_text='This will show beneath the image.', required=False))], max_num=8, min_num=8))], blank=True, use_json_field=True)),
                ('license_title', models.CharField(default='License and Attributions')),
                ('license_block', wagtail.fields.RichTextField(blank=True)),
                ('banner_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('video_overlay_icon', models.ForeignKey(blank=True, help_text='This icon will show on top of the video previews in this section; this should either be a play button, or nothing at all.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
