# Generated by Django 4.2.7 on 2024-10-08 19:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0030_multimediapage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='image_previews',
            field=wagtail.fields.StreamField([('preview', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock(help_text='The link to the image source (if known).', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('short_desc', wagtail.blocks.CharBlock(help_text='This will show beneath the image.', required=False))], max_num=8, min_num=8))], blank=True, use_json_field=True),
        ),
    ]
