# Generated by Django 4.2.7 on 2024-10-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0031_alter_multimediapage_image_previews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimediapage',
            old_name='banner_description',
            new_name='intro',
        ),
    ]
