# Generated by Django 4.2.7 on 2024-10-09 16:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0032_rename_banner_description_multimediapage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='video_previews',
            field=wagtail.fields.StreamField([('preview', wagtail.blocks.StructBlock([('link', wagtail.blocks.URLBlock(help_text="This link should be in the format of 'https://www.youtube.com/watch?v=[code]', as opposed to a share link.")), ('short_desc', wagtail.blocks.CharBlock(help_text='This will show beneath the image.', required=False))], max_num=8, min_num=8))], blank=True, use_json_field=True),
        ),
    ]
