# Generated by Django 4.2.7 on 2024-10-21 22:04

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('misc', '0034_alter_codeofconductpage_our_policies_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('brief_body_text', wagtail.fields.RichTextField(blank=True)),
                ('table_of_contents_title', models.CharField(default='Table of Contents')),
                ('show_table_of_contents', models.BooleanField()),
                ('body_sections', wagtail.fields.StreamField([('blocks', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('body', 1)]], {})}, help_text='These sections will automatically populate the table of contents if the table of contents is set to show.', null=True)),
                ('our_policies_title', models.CharField(default='Our Policies')),
                ('our_policies_links', wagtail.fields.StreamField([('blocks', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."}), 5: ('wagtail.blocks.StreamBlock', [[('page', 1), ('url', 2), ('document', 3), ('other', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 5)]], {})}, help_text='Links to be shown under the Our Policies section.', null=True)),
                ('question_block_title', models.CharField(default='Have a question about our policies?')),
                ('question_block_button_text', models.CharField(default='Contact HOT')),
                ('question_block_button_link', wagtail.fields.StreamField([('page', 0), ('url', 1), ('document', 2), ('other', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
