# Generated by Django 4.2.7 on 2024-10-21 22:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('misc', '0035_generalpolicypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPolicyOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('our_policies_title', models.CharField(default='Our Policies')),
                ('our_policies_links', wagtail.fields.StreamField([('blocks', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."}), 5: ('wagtail.blocks.StreamBlock', [[('page', 1), ('url', 2), ('document', 3), ('other', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('text', 0), ('link', 5)]], {})}, help_text='Links to be shown under the Our Policies section of the child policy pages. This list will automatically include all pages that are a child of this page, so please only add links to any externally-hosted policies (or policies that are documents)! This list of policies will appear after the child pages.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='codeofconductpage',
            name='our_policies_links',
        ),
        migrations.RemoveField(
            model_name='codeofconductpage',
            name='our_policies_title',
        ),
        migrations.RemoveField(
            model_name='generalpolicypage',
            name='our_policies_links',
        ),
        migrations.RemoveField(
            model_name='generalpolicypage',
            name='our_policies_title',
        ),
        migrations.RemoveField(
            model_name='privacypolicypage',
            name='our_policies_links',
        ),
        migrations.RemoveField(
            model_name='privacypolicypage',
            name='our_policies_title',
        ),
    ]
