# Generated by Django 4.2.7 on 2024-10-29 18:58

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0037_ourapproachpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourapproachpage',
            name='what_we_do_items',
            field=wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='ourapproachpage',
            name='what_we_do_title',
            field=models.CharField(default='What We Do'),
        ),
    ]
