# Generated by Django 4.2.7 on 2024-10-29 18:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0038_ourapproachpage_what_we_do_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourapproachpage',
            name='what_we_do_items',
            field=wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_num': 3, 'min_num': 3})}),
        ),
    ]
