# Generated by Django 4.2.7 on 2024-10-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('misc', '0040_ourapproachpage_black_box_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourapproachpage',
            name='hot_envisions_bg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
