# Generated by Django 4.2.7 on 2024-11-04 20:03

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0041_ourapproachpage_hot_envisions_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourapproachpage',
            name='our_toolbox_items',
            field=wagtail.fields.StreamField([('block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('icon', 0), ('text', 1)]], {'max_num': 6, 'min_num': 6})}),
        ),
        migrations.AlterField(
            model_name='ourapproachpage',
            name='what_happens_items',
            field=wagtail.fields.StreamField([('block', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('icon', 0), ('text', 1)]], {'max_num': 4, 'min_num': 4})}),
        ),
    ]
