# Generated by Django 4.2.7 on 2025-03-28 18:22

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0042_alter_ourapproachpage_our_toolbox_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='map_previews',
            field=wagtail.fields.StreamField([('preview', 3)], blank=True, block_lookup={0: ('wagtail.blocks.URLBlock', (), {'help_text': 'The link to the image source (if known).', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'This will show beneath the image.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('link', 0), ('image', 1), ('short_desc', 2)]], {'max_num': 8, 'min_num': 8})}),
        ),
    ]
