# Generated by Django 5.2.16 on 2026-09-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0043_multimediapage_map_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuspage',
            name='error_text',
            field=models.CharField(default='Please correct the errors and try again.'),
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='thank_you_text',
            field=models.CharField(default='Thank you, your message has been sent.'),
        ),
    ]
