version: "3.11"
services:
  web:
    image: "ghcr.io/hotosm/website/backend:${TAG_OVERRIDE:-debug}"
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
      args:
        APP_VERSION: "${TAG_OVERRIDE:-main}"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "docker.io/postgres:${POSTGRES_TAG:-16-alpine3.18}"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
