version: "3.9"
services:
  web:
    image: "ghcr.io/hotosm/website/backend:${TAG_OVERRIDE:-debug}"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
