version: "3.9"
services:
  web:
    image: "ghcr.io/hotosm/website/backend:${TAG_OVERRIDE:-main}"
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        APP_VERSION: "${TAG_OVERRIDE:-main}"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "docker.io/postgres:${POSTGRES_TAG:-16-alpine3.18}"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
