version: "3.11"
services:
  web:
    image: "ghcr.io/hotosm/website/backend:${TAG_OVERRIDE:-debug}"
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server
    command: >
      bash -c "./wait-for-it.sh db:5432 -- sleep 10 && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: test
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data:
