{{- if .Values.migrationJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django.fullname" . }}-migrate
  labels:
    {{- include "django.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
    tag: "{{ .Values.image.tag }}"
spec:
  activeDeadlineSeconds: {{ default 900 .Values.migrationJob.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migrate-job
        {{- include "django.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: migrate-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.migrationJob.command | toJson }}
          {{- if .Values.migrationJob.resources }}
          resources:
            {{- toYaml .Values.migrationJob.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
