# Generated by Django 4.2.7 on 2024-05-13 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_individualnewspage_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualnewspage',
            old_name='description',
            new_name='article_body',
        ),
    ]
