# Generated by Django 4.2.7 on 2024-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_description_individualnewspage_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnewspage',
            name='related_news_title',
            field=models.CharField(default='Related News'),
        ),
        migrations.AddField(
            model_name='individualnewspage',
            name='related_projects_title',
            field=models.CharField(default='Related Projects'),
        ),
        migrations.AddField(
            model_name='individualnewspage',
            name='view_all_news_text',
            field=models.CharField(default='View all News'),
        ),
    ]
