# Generated by Django 4.2.7 on 2024-05-13 21:57

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_individualnewspage_test_thing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualnewspage',
            name='test_thing',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='related_news',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='related_projects',
        ),
        migrations.AddField(
            model_name='individualnewspage',
            name='related_news',
            field=wagtail.fields.StreamField([('news_page', wagtail.blocks.PageChooserBlock(page_type=['news.IndividualNewsPage']))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='individualnewspage',
            name='related_projects',
            field=wagtail.fields.StreamField([('project_page', wagtail.blocks.PageChooserBlock(page_type=['projects.IndividualProjectPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
