# Generated by Django 4.2.7 on 2024-05-13 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_individualnewspage_test_thing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnewspage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
    ]
