# Generated by Django 4.2.7 on 2024-05-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newstag_individualnewspage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnewspage',
            name='news_read_more_text',
            field=models.CharField(default='Read More'),
        ),
    ]
