# Generated by Django 4.2.7 on 2024-06-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_individualnewspage_authors_posted_by_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualnewspage',
            name='date',
            field=models.DateField(help_text='Post date'),
        ),
    ]
