# Generated by Django 4.2.7 on 2024-06-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('news', '0018_alter_individualnewspage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('authors_posted_by_text', models.CharField(default='Posted by', help_text="The text which appears prior to the authors names; with 'posted by', the text displays as 'posted by [author]'.")),
                ('authors_posted_on_text', models.CharField(default='on', help_text="The text which appears prior to the date; with 'on', it would display as 'on [date]'.")),
                ('related_projects_title', models.CharField(default='Related Projects')),
                ('related_news_title', models.CharField(default='Related News')),
                ('view_all_news_text', models.CharField(default='View all News')),
                ('view_all_news_url', models.URLField(blank=True)),
                ('news_read_more_text', models.CharField(default='Read More')),
                ('categories_title', models.CharField(default='Categories')),
                ('tags_title', models.CharField(default='Tags')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='authors_posted_by_text',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='authors_posted_on_text',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='categories_title',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='news_read_more_text',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='related_news_title',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='related_projects_title',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='tags_title',
        ),
        migrations.RemoveField(
            model_name='individualnewspage',
            name='view_all_news_text',
        ),
    ]
