# Generated by Django 4.2.7 on 2024-06-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_newsownerpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsownerpage',
            name='category_select',
            field=models.CharField(default='Select Categories'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='enter_tag_hint',
            field=models.CharField(default='Enter tag'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='keyword_search_hint',
            field=models.CharField(default='Search by keyword'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='remove_filters_text',
            field=models.CharField(default='Remove All Filters'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='results_text',
            field=models.CharField(default='Results'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='search_button_text',
            field=models.CharField(default='Search'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='sort_by_new',
            field=models.CharField(default='Sort by New'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='sort_by_old',
            field=models.CharField(default='Sort by Old'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='sort_by_titlea',
            field=models.CharField(default='Sort by Title Alphabetical'),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='sort_by_titlez',
            field=models.CharField(default='Sort by Title Reverse Alphabetical'),
        ),
    ]
