# Generated by Django 4.2.7 on 2024-10-07 18:04

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_remove_newsownerpage_view_all_news_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnewspage',
            name='associated_hubs',
            field=wagtail.fields.StreamField([('region_hub', wagtail.blocks.PageChooserBlock(page_type=['mapping_hubs.IndividualMappingHubPage']))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='newsownerpage',
            name='hubs_title',
            field=models.CharField(default='Associated Hubs'),
        ),
    ]
