# Generated by Django 4.2.7 on 2024-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_alter_individualnewspage_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsownerpage',
            name='applied_text',
            field=models.CharField(default='applied', help_text='This will be a suffix to a number, used to indicate how many filters are applied currently in some field.'),
        ),
    ]
