# Generated by Django 4.2.7 on 2025-03-06 20:45

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_newsownerpage_applied_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnewspage',
            name='test_field',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
    ]
