# Generated by Django 4.2.7 on 2025-03-06 22:44

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_individualnewspage_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualnewspage',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='individualnewspage',
            name='article_body',
            field=wagtail.fields.StreamField([('text_block', 0), ('md_block', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote']}), 1: ('wagtailmarkdown.blocks.MarkdownBlock', (), {})}, null=True),
        ),
    ]
