# Generated by Django 4.2.7 on 2025-03-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('news', '0029_alter_individualnewspage_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsownerpage',
            name='fallback_image',
            field=models.ForeignKey(blank=True, help_text='If no cover image is provided for a news post, this image will display instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
