# Generated by Django 4.2.27 on 2026-01-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_alter_individualnewspage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualnewspage',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Optional custom CSS for this news post only.'),
        ),
    ]
