# Generated by Django 4.2.7 on 2024-05-21 21:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualMappingHubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_hub_text_white', models.CharField(default='Open Mapping')),
                ('header_hub_text_red', models.CharField(default='Hub')),
                ('header_project_link_text', models.CharField(default='Project')),
                ('header_project_link_url', models.URLField(blank=True)),
                ('header_news_link_text', models.CharField(default='News')),
                ('header_news_link_url', models.URLField(blank=True)),
                ('header_events_link_text', models.CharField(default='Events')),
                ('header_events_link_url', models.URLField(blank=True)),
                ('header_carousel_entries', wagtail.fields.StreamField([('carousel_entry', wagtail.blocks.StreamBlock([('slides', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='Slide header', required=True)), ('body', wagtail.blocks.CharBlock(help_text='Slide body', required=True)), ('button_text', wagtail.blocks.CharBlock(help_text='Text to display on the button', required=True)), ('button_link', wagtail.blocks.URLBlock(blank=True, help_text='URL to link to', required=False))]))], max_num=3, min_num=3))], blank=True, null=True, use_json_field=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('main_body_text', wagtail.fields.RichTextField(blank=True)),
                ('project_section_title', models.CharField()),
                ('project_section_link_text', models.CharField(blank=True)),
                ('project_section_link_url', models.URLField(blank=True)),
                ('news_section_title', models.CharField()),
                ('news_section_description', wagtail.fields.RichTextField(blank=True)),
                ('news_section_link_text', models.CharField(blank=True)),
                ('news_section_link_url', models.URLField(blank=True)),
                ('events_section_title', models.CharField()),
                ('events_section_description', wagtail.fields.RichTextField(blank=True)),
                ('events_section_link_text', models.CharField(blank=True)),
                ('events_section_link_url', models.URLField(blank=True)),
                ('partners_section_title', models.CharField(default='Meet Our Partners')),
                ('partners_section_link_text', models.CharField(default='View All')),
                ('partners_section_link_url', models.URLField(blank=True)),
                ('contact_section_title', models.CharField(default='Contact Us')),
                ('contact_section_description', wagtail.fields.RichTextField(blank=True)),
                ('contact_section_links', wagtail.fields.StreamField([('contact_link', wagtail.blocks.StreamBlock([('blocks', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.URLBlock(required=True))]))]))], blank=True, use_json_field=True)),
                ('subscribe_box_text', models.CharField(blank=True)),
                ('subscribe_box_signup_text', models.CharField(default='Sign Up')),
                ('subscribe_box_signup_link', models.URLField(blank=True)),
                ('explore_section_title', models.CharField(default='Explore Other Hubs')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
