# Generated by Django 4.2.7 on 2024-05-21 23:09

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0002_individualmappinghubpage_main_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_carousel_entries',
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='header_carousel',
            field=wagtail.fields.StreamField([('carousel_entry', wagtail.blocks.StreamBlock([('slides', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(help_text='Slide header', required=True)), ('body', wagtail.blocks.CharBlock(help_text='Slide body', required=True)), ('action_button', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Text to display on the button', required=True)), ('link', wagtail.blocks.URLBlock(blank=True, help_text='URL to link to', required=False))], help_text='Button to display on the slide', required=False))]))], max_num=3, min_num=3))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='individualmappinghubpage',
            name='header_project_link_text',
            field=models.CharField(default='Projects'),
        ),
    ]
