# Generated by Django 4.2.7 on 2024-05-22 16:12

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_partner_partner_logo_alter_partner_partner_url'),
        ('mapping_hubs', '0004_alter_individualmappinghubpage_contact_section_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.partner'),
        ),
    ]
