# Generated by Django 4.2.7 on 2024-05-22 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('mapping_hubs', '0005_individualmappinghubpage_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmappinghubpage',
            name='main_external_hub_image',
            field=models.ForeignKey(blank=True, help_text='A larger image that represents this hub which may be shown on other pages. This should be in a 2:1 aspect ratio; ideally, at least 400x200 pixels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='individualmappinghubpage',
            name='main_icon',
            field=models.ForeignKey(blank=True, help_text='The main icon that should show for this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
