# Generated by Django 4.2.7 on 2024-05-22 21:35

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0006_alter_individualmappinghubpage_main_external_hub_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='dogear_boxes',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.URLBlock(blank=True, required=False))]))], blank=True, use_json_field=True),
        ),
    ]
