# Generated by Django 4.2.7 on 2024-07-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('mapping_hubs', '0009_openmappinghubspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openmappinghubspage',
            old_name='banner_description',
            new_name='header_description',
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
