# Generated by Django 4.2.7 on 2024-07-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0010_rename_banner_description_openmappinghubspage_header_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmappinghubspage',
            name='hub_text',
            field=models.CharField(default='Hub', help_text="The text following a hub's name; i.e., if this field is 'Hub', the title for 'Asia-Pacific' would become 'Asia-Pacific Hub'."),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='learn_more_text',
            field=models.CharField(default='Learn More about', help_text="The text preceeding the hub's name in the link text; i.e., if this field is 'Learn More about', the link text for 'Asia-Pacific Hub' would become 'Learn More about Asia-Pacific Hub'."),
        ),
    ]
