# Generated by Django 4.2.7 on 2024-07-04 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('mapping_hubs', '0011_openmappinghubspage_hub_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingHubProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('load_more_projects_text', models.CharField(default='Load More Projects')),
                ('projects_by_hub_title', models.CharField(default='See Projects by Open Mapping Hub')),
                ('red_box_title', models.CharField(default='Start Mapping')),
                ('red_box_link_text', models.CharField(default='Start Mapping')),
                ('red_box_link_url', models.URLField(blank=True, null=True)),
                ('black_box_title', models.CharField(default='Check many opportunities to get involved with HOT!')),
                ('black_box_link_text', models.CharField(default='Get Involved with HOT')),
                ('black_box_link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
