# Generated by Django 4.2.7 on 2024-08-02 19:40

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0013_alter_mappinghubprojectspage_black_box_link_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='contact_section_title',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='events_section_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='explore_section_title',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_events_link_text',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_events_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_hub_text_red',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_hub_text_white',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_news_link_text',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_news_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_project_link_text',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_project_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='news_section_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='partners_section_link_text',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='partners_section_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='partners_section_title',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='project_section_link_url',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='subscribe_box_signup_link',
        ),
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='subscribe_box_signup_text',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='black_box_link_url',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='red_box_link_url',
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='events_section_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='header_project_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='news_section_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='project_section_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='subscribe_box_signup_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='black_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='contact_section_title',
            field=models.CharField(default='Contact Us'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='explore_section_title',
            field=models.CharField(default='Explore Other Hubs'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_events_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_events_link_text',
            field=models.CharField(default='Events'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_hub_text_red',
            field=models.CharField(default='Hub'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_hub_text_white',
            field=models.CharField(default='Open Mapping'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_news_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_news_link_text',
            field=models.CharField(default='News'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='header_project_link_text',
            field=models.CharField(default='Projects'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='partners_section_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='partners_section_link_text',
            field=models.CharField(default='View All'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='partners_section_title',
            field=models.CharField(default='Meet Our Partners'),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='red_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='mappinghubprojectspage',
            name='subscribe_box_signup_text',
            field=models.CharField(default='Sign Up'),
        ),
        migrations.AlterField(
            model_name='individualmappinghubpage',
            name='contact_section_links',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='individualmappinghubpage',
            name='dogear_boxes',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('link_text', wagtail.blocks.CharBlock(required=True)), ('link_url', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, required=False))]))], blank=True, help_text="These are, for example, the 'Grants' and 'Map and Chat Hour' boxes in the Asia-Pacific page. Please only add these in pairs of 2!", use_json_field=True),
        ),
    ]
