# Generated by Django 4.2.7 on 2024-08-02 19:46

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0014_remove_individualmappinghubpage_contact_section_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='contact_section_title',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='explore_section_title',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_events_link',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_events_link_text',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_hub_text_red',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_hub_text_white',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_news_link',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_news_link_text',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='header_project_link_text',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='partners_section_link',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='partners_section_link_text',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='partners_section_title',
        ),
        migrations.RemoveField(
            model_name='mappinghubprojectspage',
            name='subscribe_box_signup_text',
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='contact_section_title',
            field=models.CharField(default='Contact Us'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='explore_section_title',
            field=models.CharField(default='Explore Other Hubs'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_events_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_events_link_text',
            field=models.CharField(default='Events'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_hub_text_red',
            field=models.CharField(default='Hub'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_hub_text_white',
            field=models.CharField(default='Open Mapping'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_news_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_news_link_text',
            field=models.CharField(default='News'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='header_project_link_text',
            field=models.CharField(default='Projects'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='partners_section_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='partners_section_link_text',
            field=models.CharField(default='View All'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='partners_section_title',
            field=models.CharField(default='Meet Our Partners'),
        ),
        migrations.AddField(
            model_name='openmappinghubspage',
            name='subscribe_box_signup_text',
            field=models.CharField(default='Sign Up'),
        ),
    ]
