# Generated by Django 4.2.7 on 2024-09-17 19:56

import app.core.models
from django.db import migrations
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0018_alter_individualmappinghubpage_contact_section_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='partners',
        ),
        migrations.AddField(
            model_name='individualmappinghubpage',
            name='partner_list',
            field=wagtail.fields.StreamField([('partner', wagtail.snippets.blocks.SnippetChooserBlock(app.core.models.Partner))], blank=True, null=True, use_json_field=True),
        ),
    ]
