# Generated by Django 4.2.7 on 2024-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0019_remove_individualmappinghubpage_partners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmappinghubspage',
            name='learn_more_text',
            field=models.CharField(default='Learn More'),
        ),
    ]
