# Generated by Django 4.2.7 on 2024-11-06 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0023_openmappinghubspage_header_project_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MappingHubProjectsPage',
        ),
    ]
