# Generated by Django 4.2.7 on 2024-11-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0024_delete_mappinghubprojectspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmappinghubpage',
            name='header_project_link',
        ),
    ]
