# Generated by Django 4.2.7 on 2024-07-30 22:21

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='cta_button_link_text',
        ),
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='cta_button_link_url',
        ),
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='cta_description',
        ),
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='go_back_link',
        ),
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='go_back_text',
        ),
        migrations.RemoveField(
            model_name='individualtechstackpage',
            name='links_title',
        ),
        migrations.AddField(
            model_name='techproductsuitepage',
            name='tech_stack_cta_button_link_text',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='techproductsuitepage',
            name='tech_stack_cta_button_link_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='techproductsuitepage',
            name='tech_stack_cta_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='techproductsuitepage',
            name='tech_stack_cta_title',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='techproductsuitepage',
            name='tech_stack_go_back_text',
            field=models.CharField(default='Go Back to'),
        ),
        migrations.AddField(
            model_name='techproductsuitepage',
            name='tech_stack_links_title',
            field=models.CharField(default='Links'),
        ),
        migrations.AlterField(
            model_name='techproductsuitepage',
            name='black_box_link_text',
            field=models.CharField(default='View tech news'),
        ),
        migrations.AlterField(
            model_name='techproductsuitepage',
            name='black_box_title',
            field=models.CharField(default='Tech News'),
        ),
        migrations.AlterField(
            model_name='techproductsuitepage',
            name='red_box_link_text',
            field=models.CharField(default="View HOT's GitHub"),
        ),
        migrations.AlterField(
            model_name='techproductsuitepage',
            name='red_box_title',
            field=models.CharField(default='HOT GitHub'),
        ),
    ]
