# Generated by Django 4.2.7 on 2024-07-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_remove_individualtechstackpage_cta_button_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techproductsuitepage',
            name='product_suite_learn_more_text',
            field=models.CharField(default='Learn more about', help_text="Prefix text to be shown in page previews for the product suite section; if the page being previewed is named 'Tasking Manager', and this field is 'Learn more about', they would combine to be 'Learn more about Tasking Manager'."),
        ),
        migrations.AlterField(
            model_name='techproductsuitepage',
            name='tech_stack_go_back_text',
            field=models.CharField(default='Go Back to', help_text="Prefix text to be shown at the bottom of page for going back; this will always refer to the parent page, so if the parent page is 'Tools & Resources', and this field is 'Go Back to', they would combine to be 'Go Back to Tools & Resources'."),
        ),
    ]
