# Generated by Django 4.2.7 on 2024-09-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_remove_newsownerpage_view_all_news_url_and_more'),
        ('tech', '0004_alter_individualtechstackpage_link_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techproductsuitepage',
            name='category_filter_selector',
            field=models.ForeignKey(blank=True, help_text="The 'Tech News' link will be appended with a filter for this category. The selected category should be the Tech category.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.newscategory'),
        ),
    ]
