# Generated by Django 4.2.7 on 2024-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_techproductsuitepage_category_filter_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techproductsuitepage',
            name='product_suite_learn_more_text',
            field=models.CharField(default='Learn more'),
        ),
    ]
