# Generated by Django 4.2.7 on 2024-06-03 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0008_alter_individualmappinghubpage_dogear_boxes'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmemberpage',
            name='location',
        ),
        migrations.AddField(
            model_name='individualmemberpage',
            name='location_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapping_hubs.individualmappinghubpage'),
        ),
    ]
