# Generated by Django 4.2.7 on 2024-07-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_individualmemberpage_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualmemberpage',
            old_name='introduction',
            new_name='intro',
        ),
    ]
