# Generated by Django 4.2.7 on 2024-07-09 21:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('members', '0003_rename_introduction_individualmemberpage_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberGroupOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('search_placeholder', models.CharField(default='Search by name')),
                ('filter_by_country', models.CharField(default='Filter by Country')),
                ('sort_by_titlea', models.CharField(default='Sort by Title Alphabetical')),
                ('sort_by_titlez', models.CharField(default='Sort by Title Reverse Alphabetical')),
                ('load_more_text', models.CharField(default='Load more', help_text="This will be a prefix to the title of the page; i.e., if the page title is 'Voting members', and this field is 'Load more', this will end up appearing as 'Load more Voting members'.")),
                ('footer_box_title', models.CharField(default='Work for HOT')),
                ('footer_box_description', wagtail.fields.RichTextField(blank=True)),
                ('footer_box_button_text', models.CharField(default='Check our Job Opportunities')),
                ('footer_box_button_link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberGroupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Appears in the header.')),
                ('body_intro', wagtail.fields.RichTextField(blank=True)),
                ('body_description', wagtail.fields.RichTextField(blank=True)),
                ('desktop_size_items_per_row', models.SmallIntegerField(default=6, help_text='The number of members shown per row on desktop sizes.', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)])),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
