# Generated by Django 4.2.7 on 2024-07-09 22:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membergroupownerpage_membergrouppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmemberpage',
            name='member_groups',
            field=wagtail.fields.StreamField([('member_group', wagtail.blocks.PageChooserBlock(page_type=['members.MemberGroupPage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
