# Generated by Django 4.2.7 on 2024-07-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_individualmemberpage_member_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergrouppage',
            name='hub_shown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='membergrouppage',
            name='position_shown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
