# Generated by Django 4.2.7 on 2024-07-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_membergrouppage_hub_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergrouppage',
            name='show_search_options',
            field=models.BooleanField(default=True),
        ),
    ]
