# Generated by Django 4.2.7 on 2024-07-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_membergrouppage_show_search_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroupownerpage',
            name='search_button_text',
            field=models.CharField(default='Search'),
        ),
    ]
