# Generated by Django 4.2.7 on 2024-07-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_membergroupownerpage_search_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroupownerpage',
            name='view_all_text',
            field=models.CharField(default='View all'),
        ),
    ]
