# Generated by Django 4.2.7 on 2024-10-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_remove_membergroupownerpage_footer_box_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroupownerpage',
            name='remove_filters_text',
            field=models.CharField(default='Remove All Filters'),
        ),
    ]
