# Generated by Django 4.2.7 on 2024-10-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_membergroupownerpage_footer_box_button_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='membergroupownerpage',
            name='applied_text',
            field=models.CharField(default='applied', help_text='This will be a suffix to a number, used to indicate how many filters are applied currently in some field.'),
        ),
    ]
