# Generated by Django 4.2.7 on 2025-03-10 18:40

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_membergroupownerpage_applied_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmemberpage',
            name='intro',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
