# Generated by Django 4.2.7 on 2025-03-13 17:31

from django.db import migrations, models
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_individualmemberpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualmemberpage',
            name='country',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='individualmemberpage',
            name='intro',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='individualmemberpage',
            name='position',
            field=models.CharField(blank=True),
        ),
    ]
