# Generated by Django 4.2.7 on 2025-03-13 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('members', '0019_individualmemberpage_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberownerpage',
            name='fallback_avatar',
            field=models.ForeignKey(blank=True, help_text="If a member doesn't have a profile picture set, this image will show instead.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
