# Generated by Django 4.2.7 on 2025-03-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_individualmemberpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmemberpage',
            name='intro',
        ),
    ]
