# Generated by Django 4.2.7 on 2024-07-15 18:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualVolunteerOpportunityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('posters', wagtail.fields.StreamField([('poster', wagtail.blocks.PageChooserBlock(page_type=['members.IndividualMemberPage']))], blank=True, null=True, use_json_field=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('article_body', wagtail.fields.StreamField([('text_block', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote']))], blank=True, null=True, use_json_field=True)),
                ('contact_description', wagtail.fields.RichTextField(blank=True)),
                ('application_description', wagtail.fields.RichTextField(blank=True)),
                ('application_date', models.DateField()),
                ('location_text', models.CharField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='VolunteerOpportunityOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('posted_by_prefix_text', models.CharField(default='Posted by')),
                ('contact_title', models.CharField(default='Contact')),
                ('application_date_title', models.CharField(default='Application Date')),
                ('location_title', models.CharField(default='Location')),
                ('share_text', models.CharField(default='Share')),
                ('go_back_text', models.CharField(default='Go Back to Volunteer Opportunities')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
