# Generated by Django 4.2.7 on 2024-07-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_opportunities', '0002_volunteeropportunityownerpage_aside_block_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunityownerpage',
            name='open_opportunities_deadline_text',
            field=models.CharField(default='Deadline'),
        ),
        migrations.AddField(
            model_name='volunteeropportunityownerpage',
            name='open_opportunities_learn_more_text',
            field=models.CharField(default='Learn More'),
        ),
        migrations.AddField(
            model_name='volunteeropportunityownerpage',
            name='open_opportunities_location_text',
            field=models.CharField(default='Location'),
        ),
    ]
