# Generated by Django 4.2.7 on 2024-07-16 17:57

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_opportunities', '0003_volunteeropportunityownerpage_open_opportunities_deadline_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunityownerpage',
            name='no_opportunities_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteeropportunityownerpage',
            name='no_opportunities_title',
            field=models.CharField(default='There are no current openings.'),
        ),
    ]
