# Generated by Django 4.2.7 on 2024-09-24 21:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunitiesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_text', wagtail.fields.RichTextField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('positions_title', models.CharField(default='Open Positions')),
                ('sidebar_block_text', wagtail.fields.RichTextField(blank=True)),
                ('rfp_banner_title', models.CharField(default='Request for Proposals')),
                ('rfp_banner_description', wagtail.fields.RichTextField(blank=True)),
                ('rfp_banner_button_text', models.CharField(default='View all request for proposals')),
                ('rfp_banner_button_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('red_box_title', models.CharField(default='Join a working group')),
                ('red_box_link_text', models.CharField(default='Working Groups')),
                ('red_box_link_url', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('black_box_title', models.CharField(default='Contact a mapping community')),
                ('black_box_link_text', models.CharField(default='Community Contact')),
                ('black_box_link_url', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('rfp_banner_image', models.ForeignKey(blank=True, help_text='RFP banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
