# Generated by Django 4.2.7 on 2024-09-24 21:29

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopportunitiespage',
            name='black_box_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopportunitiespage',
            name='red_box_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobopportunitiespage',
            name='black_box_link_text',
            field=models.CharField(default='Learn the benefits of working for HOT'),
        ),
        migrations.AlterField(
            model_name='jobopportunitiespage',
            name='black_box_title',
            field=models.CharField(default='Work Culture & Benefits'),
        ),
        migrations.AlterField(
            model_name='jobopportunitiespage',
            name='red_box_link_text',
            field=models.CharField(default='Salary Framework'),
        ),
        migrations.AlterField(
            model_name='jobopportunitiespage',
            name='red_box_title',
            field=models.CharField(default='HOT Salary Framework'),
        ),
    ]
