# Generated by Django 4.2.7 on 2024-07-15 20:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualRequestForProposalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('posters', wagtail.fields.StreamField([('poster', wagtail.blocks.PageChooserBlock(page_type=['members.IndividualMemberPage']))], blank=True, null=True, use_json_field=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('article_body', wagtail.fields.StreamField([('text_block', wagtail.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'document-link', 'image', 'embed', 'code', 'blockquote']))], blank=True, null=True, use_json_field=True)),
                ('role', models.CharField(blank=True)),
                ('application_close_date', models.DateField(blank=True)),
                ('project_duration', models.CharField(blank=True)),
                ('work_location', models.CharField(blank=True)),
                ('contract_type', models.CharField(blank=True)),
                ('direct_contact', models.CharField(blank=True)),
                ('submission_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RequestForProposalOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('posted_by_prefix_text', models.CharField(default='Posted by')),
                ('terms_of_reference_title', models.CharField(default='Terms of Reference')),
                ('role_title', models.CharField(default='Role:')),
                ('application_close_title', models.CharField(default='Application Close Date:')),
                ('project_duration_title', models.CharField(default='Duration of Project:')),
                ('work_location_title', models.CharField(default='Work Location:')),
                ('contract_type_title', models.CharField(default='Type of Contract:')),
                ('direct_contact_title', models.CharField(default='Direct Contact:')),
                ('cta_title', models.CharField(blank=True)),
                ('submission_email_button', models.CharField(default='Submission Email')),
                ('go_back_text', models.CharField(default='Go Back to Request for Proposals')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
