# Generated by Django 4.2.7 on 2024-07-16 21:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('rfp', '0002_individualrequestforproposalpage_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='aside_block_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='aside_block_title',
            field=models.CharField(default='Still have questions?'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='current_rfps_title',
            field=models.CharField(default='Current RFPs'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='header_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_button_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_button_text',
            field=models.CharField(default='See All Job Opportunities'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_image',
            field=models.ForeignKey(blank=True, help_text='Job opportunities image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_title',
            field=models.CharField(default='See Our Job Opportunities'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='rfp_deadline_text',
            field=models.CharField(default='Deadline'),
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='rfp_location_text',
            field=models.CharField(default='Location'),
        ),
    ]
