# Generated by Django 4.2.7 on 2024-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0004_requestforproposalownerpage_no_rfps_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualrequestforproposalpage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
