# Generated by Django 4.2.7 on 2024-09-17 17:47

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0005_individualrequestforproposalpage_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_button_link',
        ),
        migrations.AddField(
            model_name='requestforproposalownerpage',
            name='job_opportunities_button_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
