# Generated by Django 4.2.7 on 2024-09-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfp', '0006_remove_requestforproposalownerpage_job_opportunities_button_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestforproposalownerpage',
            old_name='header_description',
            new_name='intro',
        ),
    ]
