# Generated by Django 4.2.7 on 2024-04-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='landing_page_cta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
