# Generated by Django 4.2.7 on 2024-04-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_landing_page_cta_homepage_hero_cta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(help_text='Write an introduction for the hero/landing page section', max_length=500, null=True),
        ),
    ]
