# Generated by Django 4.2.7 on 2024-05-28 00:22

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_get_involved_button_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_title',
            field=models.CharField(default='News'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='related_news',
            field=wagtail.fields.StreamField([('news_page', wagtail.blocks.PageChooserBlock(page_type=['news.IndividualNewsPage']))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='view_all_news_text',
            field=models.CharField(default='View all news'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='view_all_news_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='view_all_programs_link',
            field=models.URLField(blank=True),
        ),
    ]
