# Generated by Django 4.2.7 on 2024-05-28 16:35

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_news_title_homepage_related_news_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='related_news',
            new_name='displayed_news',
        ),
        migrations.AddField(
            model_name='homepage',
            name='mapping_hubs_link_text',
            field=models.CharField(default="Check out HOT's Open Mapping Hubs"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mapping_hubs_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_checkbox_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Ensure that you include a link to the privacy policy within this field.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_email_field_hint',
            field=models.CharField(default='Enter your email address...'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_email_text',
            field=models.CharField(default='Email Address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_first_name_field_hint',
            field=models.CharField(default='Enter your first name...'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_first_name_text',
            field=models.CharField(default='First Name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_last_name_field_hint',
            field=models.CharField(default='Enter your last name...'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_last_name_text',
            field=models.CharField(default='Last Name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_submit_button_text',
            field=models.CharField(default='Submit'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscribe_title',
            field=models.CharField(default='Subscribe for Updates & Announcements'),
        ),
    ]
