# Generated by Django 4.2.7 on 2024-05-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0012_homepage_who_we_are_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='our_work_background',
            field=models.ForeignKey(blank=True, help_text='Background for the entire Our Work section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
