# Generated by Django 4.2.7 on 2024-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_mapping_hubs_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mapping_hubs_hub_learn_more',
            field=models.CharField(default='Learn More'),
        ),
    ]
