# Generated by Django 4.2.7 on 2024-05-29 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0015_homepage_mapping_hubs_hub_learn_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='opportunities_image',
            field=models.ForeignKey(blank=True, help_text='Opportunities section image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
