# Generated by Django 4.2.7 on 2024-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepage_opportunities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='impact_areas_learn_more',
            field=models.CharField(default='Learn More'),
        ),
    ]
