# Generated by Django 4.2.7 on 2024-06-10 17:49

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_homepage_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('children', wagtail.blocks.StreamBlock([('nav_item', wagtail.blocks.StreamBlock([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the pagee.', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the pagee.', required=False))]))]))], blank=True, null=True, use_json_field=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
