# Generated by Django 4.2.7 on 2024-06-11 16:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_homepage_footer_candid_seal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_bottom_copyright',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_bottom_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='The links which show in the bottom right corner of the footer; Privacy Policy, Terms and Conditions, etc.', null=True, use_json_field=True),
        ),
    ]
