# Generated by Django 4.2.7 on 2024-06-11 19:27

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_homepage_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='navigation_buttons',
            field=wagtail.fields.StreamField([('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False))]))], blank=True, help_text='The buttons of the navigation; these show up last in the navbar, and, unlike regular navigation items, show up at all times on medium screens.', null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('show_in_footer', wagtail.blocks.BooleanBlock(help_text="If checked, this item (and its children) will show in the footer's navigation; otherwise, it will not show up.", required=False)), ('children', wagtail.blocks.StreamBlock([('nav_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('children', wagtail.blocks.StreamBlock([('nav_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False)), ('link_page', wagtail.blocks.PageChooserBlock(help_text='A link URL or page must be provided; if both are present, the link will default to the page.', required=False))]))], blank=True, null=True, required=False, use_json_field=True))]))], blank=True, null=True, required=False, use_json_field=True))]))], blank=True, help_text='The items of the navigation; this is shown on all pages.', null=True, use_json_field=True),
        ),
    ]
