# Generated by Django 4.2.7 on 2024-07-17 21:19

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_navigation_buttons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='e404_description',
            field=models.CharField(default="We're sorry, the page you requested could not be found."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='e404_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Links to be shown on the 404 page.', null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='e404_title',
            field=models.CharField(default='Page not found'),
        ),
    ]
