# Generated by Django 4.2.7 on 2024-07-17 21:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_homepage_e404_description_homepage_e404_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='e404_links',
            field=wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock(required=False))]))], blank=True, help_text='Links to be shown on the 404 page.', null=True, use_json_field=True),
        ),
    ]
