# Generated by Django 4.2.7 on 2024-09-17 17:08

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_homepage_top_navigation_donate_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_certifications',
            field=wagtail.fields.StreamField([('certification', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False))]))], blank=True, help_text='Certifications to be shown in the footer.', null=True, use_json_field=True),
        ),
    ]
