# Generated by Django 4.2.7 on 2024-09-23 19:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_homepage_footer_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='social_share_links',
            field=wagtail.fields.StreamField([('social', wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text="These links will be shown in pages which have a sharing widget; link URLs should be the respective social media site's share link, with the place share message's content being replaced with {}. For example, Twitter's share link would be 'https://twitter.com/intent/tweet?text={}'.", null=True, use_json_field=True),
        ),
    ]
