# Generated by Django 4.2.7 on 2024-09-26 21:45

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_homepage_social_share_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False)), ('show_in_footer', wagtail.blocks.BooleanBlock(help_text="If checked, this item (and its children) will show in the footer's navigation; otherwise, it will not show up.", required=False)), ('children', wagtail.blocks.StreamBlock([('nav_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False)), ('children', wagtail.blocks.StreamBlock([('nav_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False))]))], blank=True, null=True, required=False, use_json_field=True))]))], blank=True, null=True, required=False, use_json_field=True))]))], blank=True, help_text='The items of the navigation; this is shown on all pages.', null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navigation_buttons',
            field=wagtail.fields.StreamField([('button', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False))]))], blank=True, help_text='The buttons of the navigation; these show up last in the navbar, and, unlike regular navigation items, show up at all times on medium screens.', null=True, use_json_field=True),
        ),
    ]
