# Generated by Django 4.2.7 on 2024-11-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_homepage_gdpr_tracking_consent_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='gdpr_tracking_title',
            field=models.CharField(default='About the information we collect'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='gdpr_tracking_option_disagree',
            field=models.CharField(default='I Do Not Agree'),
        ),
    ]
