# Generated by Django 4.2.7 on 2024-07-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testpagepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotsearchablepage',
            name='intro',
        ),
        migrations.DeleteModel(
            name='TestPagePage',
        ),
    ]
