# Generated by Django 4.2.7 on 2024-07-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_hotsearchablepage_intro_delete_testpagepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HOTSearchablePage',
        ),
    ]
