# Generated by Django 4.2.7 on 2024-08-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partnertype_type_description_partnertype_type_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
    ]
