# Generated by Django 4.2.7 on 2024-08-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_remove_ourpartnerspage_call_to_action_description_and_more'),
        ('core', '0009_remove_partner_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partners.partnershiptemplatepage'),
        ),
    ]
