# Generated by Django 4.2.7 on 2024-08-14 20:01

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_remove_ourpartnerspage_call_to_action_description_and_more'),
        ('core', '0010_partner_partner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='partners.partnershiptemplatepage'),
        ),
    ]
