# Generated by Django 4.2.7 on 2024-08-14 20:59

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_partner_partner_type_partner_partner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=wagtail.fields.StreamField([('type', wagtail.blocks.PageChooserBlock(page_type=['partners.PartnershipTemplatePage']))], blank=True, null=True, use_json_field=True),
        ),
    ]
