# Generated by Django 4.2.7 on 2025-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_errorpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_is_active',
            field=models.BooleanField(default=True, help_text='If this field is unchecked, this partner will not appear in partner showcase carousels, nor the Our Partners page. They will, however, still appear in project pages that have them listed.'),
        ),
    ]
