# Generated by Django 4.2.7 on 2024-07-03 19:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('get_involved', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinvolvedpage',
            name='black_box_link_text',
            field=models.CharField(default='Contact Us'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='black_box_link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='black_box_title',
            field=models.CharField(default='Stay in Touch'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='dogear_box_link_text',
            field=models.CharField(default='Contact by Country'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='dogear_box_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='dogear_box_title',
            field=models.CharField(default='Connect with our OSM community!'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='events',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.PageChooserBlock(page_type=['events.IndividualEventPage']))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='events_title',
            field=models.CharField(default='Events'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='get_involved_community_title',
            field=models.CharField(default='Get Involved in Our Community'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='get_involved_large_panels',
            field=wagtail.fields.StreamField([('panel', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='join_us_panels',
            field=wagtail.fields.StreamField([('panel', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='join_us_title',
            field=models.CharField(default='Join Us'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='partner_with_us_button_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='partner_with_us_button_text',
            field=models.CharField(default='Partner With Us'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='partner_with_us_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='partner_with_us_image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='partner_with_us_title',
            field=models.CharField(default='Partner With Us!'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='red_box_link_text',
            field=models.CharField(default='Donate Today'),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='red_box_link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='red_box_title',
            field=models.CharField(default="Support HOT's work!"),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='view_all_events_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='view_all_events_text',
            field=models.CharField(default='View all Events'),
        ),
    ]
