# Generated by Django 4.2.7 on 2024-07-03 23:20

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0002_getinvolvedpage_black_box_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinvolvedpage',
            name='join_us_panel_read_more',
            field=models.CharField(default='Read More'),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='join_us_panels',
            field=wagtail.fields.StreamField([('panel', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('tablet_description', wagtail.blocks.RichTextBlock(blank=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
