# Generated by Django 4.2.7 on 2024-09-16 18:02

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0003_getinvolvedpage_join_us_panel_read_more_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getinvolvedpage',
            name='black_box_link_url',
        ),
        migrations.RemoveField(
            model_name='getinvolvedpage',
            name='dogear_box_link_url',
        ),
        migrations.RemoveField(
            model_name='getinvolvedpage',
            name='partner_with_us_button_link',
        ),
        migrations.RemoveField(
            model_name='getinvolvedpage',
            name='red_box_link_url',
        ),
        migrations.RemoveField(
            model_name='getinvolvedpage',
            name='view_all_events_link',
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='black_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='dogear_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='partner_with_us_button_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='red_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='getinvolvedpage',
            name='view_all_events_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='getinvolvedpage',
            name='get_involved_large_panels',
            field=wagtail.fields.StreamField([('panel', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
