# Generated by Django 4.2.7 on 2024-06-05 20:25

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualeventpage',
            name='more_events',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.PageChooserBlock(page_type=['events.IndividualEventPage']))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='individualeventpage',
            name='rsvp_link',
            field=models.URLField(blank=True, help_text='If both RSVP Description and Link are empty, the RSVP section will be hidden.'),
        ),
    ]
