# Generated by Django 4.2.7 on 2024-06-05 22:09

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_individualeventpage_more_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerpage',
            name='event_read_more_text',
            field=models.CharField(default='Read more'),
        ),
        migrations.AlterField(
            model_name='individualeventpage',
            name='rsvp_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='If this field is empty, the RSVP description will not appear.'),
        ),
        migrations.AlterField(
            model_name='individualeventpage',
            name='rsvp_link',
            field=models.URLField(blank=True, help_text='If this field is empty, the RSVP button will not appear. If both RSVP Description and Link are empty, the RSVP section will be hidden.'),
        ),
    ]
