# Generated by Django 4.2.7 on 2024-06-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventownerpage_event_read_more_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerpage',
            name='keyword_search_hint',
            field=models.CharField(default='Search by keyword'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='results_text',
            field=models.CharField(default='Results'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='search_button_text',
            field=models.CharField(default='Search'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='sort_by_new',
            field=models.CharField(default='Sort by New'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='sort_by_old',
            field=models.CharField(default='Sort by Old'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='sort_by_titlea',
            field=models.CharField(default='Sort by Title Alphabetical'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='sort_by_titlez',
            field=models.CharField(default='Sort by Title Reverse Alphabetical'),
        ),
    ]
