# Generated by Django 4.2.7 on 2024-07-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_hubs', '0013_alter_mappinghubprojectspage_black_box_link_text_and_more'),
        ('events', '0004_eventownerpage_keyword_search_hint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='EventHostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='individualeventpage',
            name='event_region_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mapping_hubs.individualmappinghubpage'),
        ),
        migrations.AddField(
            model_name='individualeventpage',
            name='event_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='individualeventpage',
            name='event_host_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventhosttype'),
        ),
    ]
