# Generated by Django 4.2.7 on 2024-07-26 18:56

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventcategory_eventhosttype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'Event Categories'},
        ),
        migrations.RemoveField(
            model_name='individualeventpage',
            name='event_category',
        ),
        migrations.AddField(
            model_name='individualeventpage',
            name='event_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='events.eventcategory'),
        ),
    ]
