# Generated by Django 4.2.7 on 2024-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerpage',
            name='event_categories_title',
            field=models.CharField(default='Categories'),
        ),
        migrations.AddField(
            model_name='eventownerpage',
            name='event_region_hub_title',
            field=models.CharField(default='Region Hub'),
        ),
    ]
