# Generated by Django 4.2.7 on 2024-07-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventhosttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventownerpage',
            name='category_select',
            field=models.CharField(default='Filter by Category'),
        ),
        migrations.AlterField(
            model_name='eventownerpage',
            name='filter_by_country',
            field=models.CharField(default='Filter by Country'),
        ),
        migrations.AlterField(
            model_name='eventownerpage',
            name='host_type_select',
            field=models.CharField(default='Filter by Host Type'),
        ),
    ]
