# Generated by Django 4.2.7 on 2024-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_eventownerpage_view_all_events_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerpage',
            name='remove_filters_text',
            field=models.CharField(default='Remove All Filters'),
        ),
    ]
