# Generated by Django 4.2.7 on 2024-10-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_individualeventpage_extended_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventownerpage',
            name='applied_text',
            field=models.CharField(default='applied', help_text='This will be a suffix to a number, used to indicate how many filters are applied currently in some field.'),
        ),
    ]
