# Generated by Django 4.2.7 on 2024-05-15 16:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', wagtail.fields.RichTextField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('stats_title', models.CharField(default='Stats')),
                ('stats', wagtail.fields.StreamField([('stat_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True)),
                ('goals_title', models.CharField(default='Goals')),
                ('goals', wagtail.fields.StreamField([('goal_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True)),
                ('projects_title', models.CharField(default='Projects')),
                ('partners_title', models.CharField(default='Meet Our Partners')),
                ('more_programs_title', models.CharField(default='More Programs')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('intro_image', models.ForeignKey(blank=True, help_text='Intro image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
