# Generated by Django 4.2.7 on 2024-05-15 21:46

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprogrampage',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.partner'),
        ),
    ]
