# Generated by Django 4.2.7 on 2024-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_individualprogrampage_more_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprogrampage',
            name='bottom_banner_text',
            field=models.CharField(default='Check out the many opportunities to get involved with HOT!'),
        ),
        migrations.AddField(
            model_name='individualprogrampage',
            name='bottom_banner_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='individualprogrampage',
            name='bottom_banner_url_text',
            field=models.CharField(default='Get Involved with HOT'),
        ),
    ]
