# Generated by Django 4.2.7 on 2024-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_individualprogrampage_bottom_banner_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprogrampage',
            name='bottom_banner_text',
            field=models.CharField(default='Check out the many opportunities to get involved with HOT!'),
        ),
    ]
