# Generated by Django 4.2.7 on 2024-06-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('programs', '0007_alter_individualprogrampage_bottom_banner_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOwnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('stats_title', models.CharField(default='Stats')),
                ('goals_title', models.CharField(default='Goals')),
                ('projects_title', models.CharField(default='Projects')),
                ('partners_title', models.CharField(default='Meet Our Partners')),
                ('view_all_partners_title', models.CharField(default='View All Partners')),
                ('view_all_partners_link', models.CharField(blank=True)),
                ('more_programs_title', models.CharField(default='More Programs')),
                ('view_all_programs_title', models.CharField(default='View All Programs')),
                ('view_all_programs_link', models.URLField(blank=True)),
                ('bottom_banner_text', models.CharField(default='Check out the many opportunities to get involved with HOT!')),
                ('bottom_banner_url', models.URLField(blank=True)),
                ('bottom_banner_url_text', models.CharField(default='Get Involved with HOT')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='bottom_banner_text',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='bottom_banner_url',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='bottom_banner_url_text',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='goals_title',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='more_programs_title',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='partners_title',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='projects_title',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='stats_title',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='view_all_partners_link',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='view_all_partners_title',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='view_all_programs_link',
        ),
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='view_all_programs_title',
        ),
    ]
