# Generated by Django 4.2.7 on 2024-09-13 22:53

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_programownerpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programownerpage',
            name='bottom_banner_url',
        ),
        migrations.RemoveField(
            model_name='programownerpage',
            name='view_all_partners_link',
        ),
        migrations.RemoveField(
            model_name='programownerpage',
            name='view_all_programs_link',
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='bottom_banner_link_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='view_all_partners_link_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='view_all_programs_link_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
