# Generated by Django 4.2.7 on 2024-09-13 22:55

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_remove_programownerpage_bottom_banner_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprogrampage',
            name='stats',
            field=wagtail.fields.StreamField([('stat_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.CharBlock())]))], blank=True, null=True, use_json_field=True),
        ),
    ]
