# Generated by Django 4.2.7 on 2024-09-17 19:39

import app.core.models
from django.db import migrations
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_alter_individualprogrampage_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprogrampage',
            name='partner_list',
            field=wagtail.fields.StreamField([('partner', wagtail.snippets.blocks.SnippetChooserBlock(app.core.models.Partner))], blank=True, null=True, use_json_field=True),
        ),
    ]
