# Generated by Django 4.2.7 on 2024-09-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_individualprogrampage_partner_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualprogrampage',
            name='partners',
        ),
    ]
