# Generated by Django 4.2.7 on 2024-11-04 23:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_programownerpage_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programownerpage',
            name='black_box_link_text',
            field=models.CharField(default='Get involved'),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='black_box_link_url',
            field=wagtail.fields.StreamField([('page', 0), ('url', 1), ('document', 2), ('other', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."})}),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='black_box_title',
            field=models.CharField(default='See the many ways to get involved with HOT and open mapping'),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='red_box_link_text',
            field=models.CharField(default='Explore projects'),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='red_box_link_url',
            field=wagtail.fields.StreamField([('page', 0), ('url', 1), ('document', 2), ('other', 3)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."})}),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='red_box_title',
            field=models.CharField(default='See all of HOT’s projects'),
        ),
    ]
