# Generated by Django 4.2.7 on 2024-11-05 18:11

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_programownerpage_black_box_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprogrampage',
            name='bigger_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='programownerpage',
            name='about_program_title',
            field=models.CharField(default='About the Program'),
        ),
    ]
