# Generated by Django 4.2.7 on 2025-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_remove_individualprogrampage_bigger_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprogrampage',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', help_text='Current status of the program', max_length=20),
        ),
        migrations.AlterField(
            model_name='programownerpage',
            name='red_box_title',
            field=models.CharField(default="See all of HOT's projects"),
        ),
    ]
