# Generated by Django 4.2.7 on 2024-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpage',
            name='search_text_midfix',
            field=models.CharField(default='returns'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='search_text_postfix',
            field=models.CharField(default='results'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='search_text_prefix',
            field=models.CharField(default='Your search for'),
        ),
    ]
