# Generated by Django 4.2.7 on 2024-06-28 19:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoWeArePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('learn_more_button_text', models.CharField(default='Learn More About Our Living Strategy')),
                ('learn_more_button_url', models.URLField(blank=True)),
                ('intro_info_blocks', wagtail.fields.StreamField([('info_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(blank=True)), ('description', wagtail.blocks.CharBlock(blank=True))]))], null=True, use_json_field=True)),
                ('our_approach_title', models.CharField(default='Our Approach')),
                ('our_approach_description', models.CharField(blank=True)),
                ('our_approach_button_url', models.URLField(blank=True)),
                ('our_approach_button_text', models.CharField(default='Our Approach')),
                ('our_people_title', models.CharField(default='Our People')),
                ('our_people_description', wagtail.fields.RichTextField(blank=True)),
                ('our_people_links', wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock(blank=True))]))], null=True, use_json_field=True)),
                ('other_page_preview_blocks', wagtail.fields.StreamField([('other_page_preview', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock())]))], null=True, use_json_field=True)),
                ('partners_title', models.CharField(default='Meet Our Partners')),
                ('partners_view_all_text', models.CharField(default='View All Partners')),
                ('partners_view_all_url', models.URLField(blank=True)),
                ('work_hot_title', models.CharField(default='Work for HOT')),
                ('work_hot_description', wagtail.fields.RichTextField(blank=True)),
                ('work_hot_button_text', models.CharField(default='View all Job Opportunities')),
                ('work_hot_button_link', models.URLField(blank=True)),
                ('our_policies_title', models.CharField(default='Our Policies')),
                ('our_policies_description', wagtail.fields.RichTextField(blank=True)),
                ('our_policies_links', wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock(blank=True))]))], null=True, use_json_field=True)),
                ('red_box_title', models.CharField(default='Annual Reports')),
                ('red_box_link_text', models.CharField(default='Access our annual report archive.')),
                ('red_box_link_url', models.URLField(blank=True, null=True)),
                ('black_box_title', models.CharField(default='Our Financial Reports')),
                ('black_box_link_text', models.CharField(default='Access older financial reports and organization bylaws in our archive.')),
                ('black_box_link_url', models.URLField(blank=True, null=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('our_approach_image', models.ForeignKey(blank=True, help_text='Our approach image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('work_hot_image', models.ForeignKey(blank=True, help_text='Work for HOT section image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
