# Generated by Django 4.2.7 on 2024-06-28 23:12

from django.db import migrations
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_partner_partner_logo_alter_partner_partner_url'),
        ('who_we_are', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whowearepage',
            name='partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.partner'),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='intro_info_blocks',
            field=wagtail.fields.StreamField([('info_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(blank=True)), ('description', wagtail.blocks.RichTextBlock(blank=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='other_page_preview_blocks',
            field=wagtail.fields.StreamField([('other_page_preview', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock())]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='our_people_links',
            field=wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock(blank=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='our_policies_links',
            field=wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.URLBlock(blank=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
