# Generated by Django 4.2.7 on 2024-07-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_we_are', '0002_whowearepage_partners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whowearepage',
            name='black_box_description',
            field=models.CharField(default='Access older financial reports and organization bylaws in our archive.'),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='red_box_description',
            field=models.CharField(default='Access our annual report archive.'),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='black_box_link_text',
            field=models.CharField(default='Check all Financial Reports'),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='red_box_link_text',
            field=models.CharField(default='Check all Annual Reports'),
        ),
    ]
