# Generated by Django 4.2.7 on 2024-07-02 17:17

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('who_we_are', '0003_whowearepage_black_box_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whowearepage',
            name='black_box_description',
            field=wagtail.fields.RichTextField(default='Access older financial reports and organization bylaws in our archive.'),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='red_box_description',
            field=wagtail.fields.RichTextField(default='Access our annual report archive.'),
        ),
    ]
