# Generated by Django 4.2.7 on 2024-08-02 22:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('who_we_are', '0004_alter_whowearepage_black_box_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whowearepage',
            name='black_box_link_url',
        ),
        migrations.RemoveField(
            model_name='whowearepage',
            name='learn_more_button_url',
        ),
        migrations.RemoveField(
            model_name='whowearepage',
            name='our_approach_button_url',
        ),
        migrations.RemoveField(
            model_name='whowearepage',
            name='partners_view_all_url',
        ),
        migrations.RemoveField(
            model_name='whowearepage',
            name='red_box_link_url',
        ),
        migrations.RemoveField(
            model_name='whowearepage',
            name='work_hot_button_link',
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='black_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='learn_more_button_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='our_approach_button_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='partners_view_all_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='red_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='whowearepage',
            name='work_hot_button_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='our_people_links',
            field=wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='whowearepage',
            name='our_policies_links',
            field=wagtail.fields.StreamField([('link_block', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, required=False))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
