# Generated by Django 4.2.7 on 2024-09-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('who_we_are', '0007_alter_whowearepage_other_page_preview_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='whowearepage',
            name='preview_learn_more_text',
            field=models.CharField(default='Learn more'),
        ),
    ]
