# Generated by Django 4.2.7 on 2024-05-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactareaspage',
            old_name='test',
            new_name='intro',
        ),
    ]
