# Generated by Django 4.2.7 on 2024-05-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('impact_areas', '0002_rename_test_impactareaspage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactareaspage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
