# Generated by Django 4.2.7 on 2024-05-06 23:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0004_impactareaspage_impact_area_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactareaspage',
            name='impact_area_blocks',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(form_classname='title')), ('description', wagtail.blocks.RichTextBlock()), ('link', wagtail.blocks.URLBlock())], null=True, use_json_field=True),
        ),
    ]
