# Generated by Django 4.2.7 on 2024-05-23 19:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('impact_areas', '0010_alter_impactareaspage_impact_area_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualImpactAreaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_text', wagtail.fields.RichTextField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('use_cases_title', models.CharField(default='Use Cases')),
                ('use_cases', wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('description', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(blank=True))]))], blank=True, null=True, use_json_field=True)),
                ('projects_title', models.CharField(default='Projects')),
                ('view_all_projects_text', models.CharField(default='View all projects')),
                ('view_all_projects_link', models.URLField(blank=True)),
                ('load_more_projects_text', models.CharField(blank=True)),
                ('explore_impact_areas_text', models.CharField(default='Explore Other Impact Areas')),
                ('red_dogear_box_title', models.CharField(blank=True)),
                ('red_dogear_box_link_text', models.CharField(blank=True)),
                ('red_dogear_box_link_url', models.URLField(blank=True)),
                ('black_dogear_box_title', models.CharField(blank=True)),
                ('black_dogear_box_link_text', models.CharField(blank=True)),
                ('black_dogear_box_link_url', models.URLField(blank=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('intro_image', models.ForeignKey(blank=True, help_text='Intro image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
