# Generated by Django 4.2.7 on 2024-06-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0013_individualimpactareapage_external_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='black_dogear_box_link_text',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='black_dogear_box_link_url',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='black_dogear_box_title',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='explore_impact_areas_text',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='load_more_projects_text',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='projects_title',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='red_dogear_box_link_text',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='red_dogear_box_link_url',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='red_dogear_box_title',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='use_cases_title',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='view_all_projects_link',
        ),
        migrations.RemoveField(
            model_name='individualimpactareapage',
            name='view_all_projects_text',
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='black_dogear_box_link_text',
            field=models.CharField(default='Get Involved with HOT'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='black_dogear_box_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='black_dogear_box_title',
            field=models.CharField(default='Check many opportunities to get involved with HOT!'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='explore_impact_areas_text',
            field=models.CharField(default='Explore Other Impact Areas'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='load_more_projects_text',
            field=models.CharField(default='Load More Projects'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='projects_title',
            field=models.CharField(default='Projects'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='red_dogear_box_link_text',
            field=models.CharField(default='View Tools & Resources'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='red_dogear_box_link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='red_dogear_box_title',
            field=models.CharField(default='Learn more about Tools & Resources and Data Access'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='use_cases_title',
            field=models.CharField(default='Use Cases'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='view_all_projects_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='view_all_projects_text',
            field=models.CharField(default='View all projects'),
        ),
    ]
