# Generated by Django 4.2.7 on 2024-06-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('impact_areas', '0014_remove_individualimpactareapage_black_dogear_box_link_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualimpactareapage',
            name='external_icon',
            field=models.ForeignKey(blank=True, help_text='The icon representing this page which is shown for previews of this page on other pages. This should be a purely black image which is ideally as wide as it is tall.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
