# Generated by Django 4.2.7 on 2024-08-01 22:06

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0015_alter_individualimpactareapage_external_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactareaspage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='header_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
