# Generated by Django 4.2.7 on 2024-08-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0016_impactareaspage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactareaspage',
            name='impact_area_blocks',
        ),
    ]
