# Generated by Django 4.2.7 on 2024-08-02 18:21

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0018_alter_individualimpactareapage_use_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualimpactareapage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='This text will not be shown on the page itself, and will instead be shown as the short description for the page for instances such as the Search page or the Impact Areas page.'),
        ),
    ]
