# Generated by Django 4.2.7 on 2024-09-03 21:39

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0019_alter_individualimpactareapage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualimpactareapage',
            name='use_cases',
            field=wagtail.fields.StreamField([('blocks', wagtail.blocks.StructBlock([('description', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, null=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
