# Generated by Django 4.2.7 on 2024-09-16 21:16

from django.db import migrations, models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact_areas', '0020_alter_individualimpactareapage_use_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactareaspage',
            name='black_dogear_box_link_url',
        ),
        migrations.RemoveField(
            model_name='impactareaspage',
            name='red_dogear_box_link_url',
        ),
        migrations.RemoveField(
            model_name='impactareaspage',
            name='view_all_projects_link',
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='black_dogear_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='learn_more_text',
            field=models.CharField(default='Learn more'),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='red_dogear_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='impactareaspage',
            name='view_all_projects_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
