# Generated by Django 4.2.7 on 2024-11-05 20:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('impact_areas', '0022_alter_impactareaspage_black_dogear_box_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualimpactareapage',
            name='description_extended',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='individualimpactareapage',
            name='external_icon',
            field=models.ForeignKey(blank=True, help_text="The icon representing this page which is shown for previews of this page on other pages. This should be a purely black image which is ideally as wide as it is tall. It also appears in the first block of this impact area's page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='individualimpactareapage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text="This image will show on the home page's previews for impact areas.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
