# Generated by Django 4.2.7 on 2024-07-04 17:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsAndResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_header', models.CharField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('learn_more_data_principles_text', models.CharField(default='Learn about our Data & Principles')),
                ('learn_more_data_principles_link', models.URLField(blank=True)),
                ('large_panels', wagtail.fields.StreamField([('panel', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('link_text', wagtail.blocks.CharBlock()), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, null=True, use_json_field=True)),
                ('resource_learning_title', models.CharField(default='Resource and Learning Centre')),
                ('resource_learning_description', wagtail.fields.RichTextField(blank=True)),
                ('get_connected_button_text', models.CharField(default='Get connect now')),
                ('get_connected_button_link', models.URLField(blank=True)),
                ('dogear_tech_news_title', models.CharField(blank=True)),
                ('dogear_tech_news_link_text', models.CharField(default='View our Tech News')),
                ('dogear_tech_news_link_url', models.URLField(blank=True)),
                ('red_box_title', models.CharField(default='Start Mapping')),
                ('red_box_link_text', models.CharField(default='Start Mapping')),
                ('red_box_link_url', models.URLField(blank=True, null=True)),
                ('black_box_title', models.CharField(default='Check many opportunities to get involved with HOT!')),
                ('black_box_link_text', models.CharField(default='Get Involved with HOT')),
                ('black_box_link_url', models.URLField(blank=True, null=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('intro_image', models.ForeignKey(blank=True, help_text='Intro image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('resource_learning_image', models.ForeignKey(blank=True, help_text='Resource and Learning Centre image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
