# Generated by Django 4.2.7 on 2024-07-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsandresourcespage',
            name='get_connected_button_text',
            field=models.CharField(default='Get connected now'),
        ),
    ]
