# Generated by Django 4.2.7 on 2024-08-19 18:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('tools_and_resources', '0003_alter_toolsandresourcespage_large_panels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMappingSolutionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('solutions', wagtail.fields.StreamField([('solution', wagtail.blocks.StructBlock([('banner', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.RichTextBlock())]))], blank=True, null=True, use_json_field=True)),
                ('cta_title', models.CharField(default='Get Started with Open Mapping')),
                ('cta_description', wagtail.fields.RichTextField(blank=True)),
                ('cta_button_text', models.CharField(default='Start Open Mapping')),
                ('cta_button_link', wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], blank=True, use_json_field=True)),
                ('go_back_prefix_text', models.CharField(default='Go Back to')),
                ('header_image', models.ForeignKey(blank=True, help_text='Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
