# Generated by Django 4.2.7 on 2024-08-19 18:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_resources', '0004_openmappingsolutionspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmappingsolutionspage',
            name='solutions',
            field=wagtail.fields.StreamField([('solution', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('banner', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.RichTextBlock()), ('items', wagtail.blocks.StreamBlock([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('links', wagtail.blocks.StreamBlock([('link', wagtail.blocks.StructBlock([('linktext', wagtail.blocks.CharBlock()), ('linkurl', wagtail.blocks.StreamBlock([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock())], required=False))]))], required=False))]))]))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
