# Generated by Django 4.2.7 on 2024-09-23 20:51

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_resources', '0006_alter_openmappingsolutionspage_cta_button_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsandresourcespage',
            name='black_box_link_url',
        ),
        migrations.RemoveField(
            model_name='toolsandresourcespage',
            name='dogear_tech_news_link_url',
        ),
        migrations.RemoveField(
            model_name='toolsandresourcespage',
            name='get_connected_button_link',
        ),
        migrations.RemoveField(
            model_name='toolsandresourcespage',
            name='learn_more_data_principles_link',
        ),
        migrations.RemoveField(
            model_name='toolsandresourcespage',
            name='red_box_link_url',
        ),
        migrations.AddField(
            model_name='toolsandresourcespage',
            name='black_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='toolsandresourcespage',
            name='dogear_tech_news_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='toolsandresourcespage',
            name='get_connected_button_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='toolsandresourcespage',
            name='learn_more_data_principles_url',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='toolsandresourcespage',
            name='red_box_link',
            field=wagtail.fields.StreamField([('page', wagtail.blocks.PageChooserBlock()), ('url', wagtail.blocks.URLBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True),
        ),
    ]
