# Generated by Django 4.2.7 on 2024-10-25 19:12

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tools_and_resources', '0009_alter_openmappingsolutionspage_cta_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmappingsolutionspage',
            name='solutions',
            field=wagtail.fields.StreamField([('solution', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {}), 5: ('wagtail.blocks.URLBlock', (), {}), 6: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Only use this option as a last resort. The other fields are preferred. In cases like email 'mailto' links, however, this field can be used. Ensure that your provided link will function as intended prior to publishing live."}), 8: ('wagtail.blocks.StreamBlock', [[('page', 4), ('url', 5), ('document', 6), ('other', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('linktext', 0), ('linkurl', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('link', 9)]], {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('icon', 3), ('title', 0), ('description', 2), ('links', 10)]], {}), 12: ('wagtail.blocks.StreamBlock', [[('item', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('banner', 1), ('description', 2), ('items', 12)]], {})}, null=True),
        ),
    ]
