name: Use hotosm Image Build workflow

on:
  push:
    branches:
      - 'main'
      - 'release/*'
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    with:
      context: .
      dockerfile: ${{ github.event_name == 'pull_request' && './Dockerfile.dev' || './Dockerfile.prod' }}
      image_name: ghcr.io/${{ github.repository }}/backend
      extra_build_args: |
        APP_VERSION=${{ github.ref_name }}
        COMMIT_REF=${{ github.sha }}
