name: Use hotosm workflow immage build fors pushes to main or release branches

on:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'
jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_pytest.yml@main
    secrets: inherit
    with:
      build_context: .
      build_dockerfile: ${{ github.event_name == 'pull_request' && './Dockerfile.dev' || './Dockerfile.prod' }}
      image_name: ghcr.io/${{ github.repository }}
      extra_build_args: |
        COMMIT_REF=${{ github.sha }}
      environment: dev
