# Use hotosm workflow immage build fors pushes to main or release branches
name: Image Build

on:
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'

jobs:
  build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    secrets: inherit
    with:
      image_name: ghcr.io/${{ github.repository }}
      build_target: prod
