name: Use hotosm workflow test_compose for pull requests to main or release branches

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'
jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@main
    with:
      image_name: ghcr.io/${{ github.repository }}/backend
      build_context: ./
      build_dockerfile: Dockerfile.dev
      extra_build_args: |
        APP_VERSION=${{ github.ref_name }}
        COMMIT_REF=${{ github.sha }}
      compose_service: web
      compose_command: /app/wait-for-it.sh db:5000 --strict -- /app/wait-for-it.sh web:8000 --strict --timeout=30 -- pytest
      compose_file: "docker-compose.dev.yml"
