name: Use hotosm workflow test_compose for pull requests to main or release branches

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'
jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@main
    secrets: inherit
    with:
      image_name: ghcr.io/${{ github.repository }}/backend
      build_dockerfile: Dockerfile.dev
      extra_build_args: |
        APP_VERSION=${{ github.ref_name }}
        COMMIT_REF=${{ github.sha }}
      compose_service: base
      compose_command: pytest
      compose_file: "docker-compose.dev.yml"
