# Use hotosm workflow test_compose for pull requests to main or release branches
name: PyTest

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'
      - 'dev'
jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@main
    secrets: inherit
    with:
      image_name: ghcr.io/${{ github.repository }}/backend
      build_dockerfile: Dockerfile
      build_target: test
      compose_service: web
      compose_command: "pytest"
      compose_file: "docker-compose.dev.yml"
      cache_extra_imgs: |
        "docker.io/postgres:16-alpine3.18"
