name: Hotosm workflow for running pytest on pull requests to main or release branches

on:
  pull_request:
    branches:
      - 'main'
      - 'release/*'

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_pytest.yml@main
    with:
      build_context: .
      build_dockerfile: ${{ github.event_name == 'pull_request' && './Dockerfile.dev' || './Dockerfile.prod' }}
      image_name: ghcr.io/${{ github.repository }}
      extra_build_args: |
        COMMIT_REF=${{ github.sha }}
      environment: dev
